wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1659247652
    t:
      1:
      - 55
      4: 3.8.13
      5: 0.12.21
      8:
      - 1
      - 3
      - 5
